export default {
  mainGoal: '건강한 서른',
  subGoal1: {
    goal: '건강',
    plan1: '12시 취침 07시 기상',
    plan2: '식단일기 기록하기',
    plan3: '음주량 줄이기',
    plan4: '9시 이후 금식',
    plan5: '과일 가까이하기',
    plan6: '체중 감량(-10kg)',
    plan7: '하루 만보 걷기',
    plan8: '탄산음료 멀리하기',
  },
  subGoal2: {
    goal: '관계',
    plan1: '불필요한 관계 정리',
    plan2: '감사함, 미안함 자주 표현하기',
    plan3: '자주 연락하기',
    plan4: '경조사 챙기기',
    plan5: '다양한 분야 사람 만나기',
    plan6: '약속시간 지키기',
    plan7: '의미없는 만남 줄이기',
    plan8: '칭찬에 인색하지 않기',
  },
  subGoal3: {
    goal: '재정',
    plan1: '가계부 작성하기',
    plan2: '30대 재정 로드맵',
    plan3: '신용카드 줄이기',
    plan4: '불필요한 소비 자제',
    plan5: '분산 관리',
    plan6: '급하게 구입하지 않기',
    plan7: '부수입 창출하기',
    plan8: '트렌드 공부',
  },
  subGoal4: {
    goal: '생활양식',
    plan1: '방 깨긋이 유지',
    plan2: '존재 지향 소유 지향',
    plan3: '많이 실패하기',
    plan4: '온종일 일에 묶여있지 않기',
    plan5: '한 번에 한 가지씩 하기',
    plan6: '느린 리듬으로 살아보기',
    plan7: '쓰지않는 물건 나눠주기',
    plan8: '물건 자주 버리기',
  },
  subGoal5: {
    goal: '성장',
    plan1: '독서 40권',
    plan2: '영화 100편',
    plan3: '온라인 프로젝트',
    plan4: '중요한 일 매일 15분 투자',
    plan5: '독립서적 출간',
    plan6: '생산성 도구 강연',
    plan7: '사이드 프로젝트',
    plan8: '영상 공부',
  },
  subGoal6: {
    goal: '삶의 질',
    plan1: '파이썬',
    plan2: '일상기록',
    plan3: '거절',
    plan4: '글쓰기',
    plan5: '와인, 위스키',
    plan6: '예술영화',
    plan7: '재능기부',
    plan8: '소설',
  },
  subGoal7: {
    goal: '자기다움',
    plan1: '유튜브 채널',
    plan2: '취향 에세이',
    plan3: '안 가본 곳 여행하기',
    plan4: '주간 모닥불',
    plan5: '종이책 출간',
    plan6: '공간 탐사',
    plan7: '운동 하나 배우기',
    plan8: 'Do',
  },
  subGoal8: {
    goal: '습관',
    plan1: '필사',
    plan2: '기상',
    plan3: '가계부',
    plan4: '운동',
    plan5: '워크 플로위',
    plan6: '영어',
    plan7: '글쓰기',
    plan8: '바인더',
  },
};
